name: Discord Product Trigger

on:
  repository_dispatch:
    types: [discord-product-trigger]
  workflow_dispatch:  # ← Ajoute ça pour le déclenchement manuel
    inputs:
      product_name:
        description: 'Nom du produit'
        required: true
        default: 'casque audio'

jobs:
  scrape-and-fill-sheet:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run scraper
        env:
          PRODUCT_NAME: ${{ github.event.client_payload.product_name || github.event.inputs.product_name }}
          GOOGLE_SHEET_ID: ${{ secrets.GOOGLE_SHEET_ID }}
          GOOGLE_CREDENTIALS_PATH: ${{ secrets.GOOGLE_CREDENTIALS_PATH }}
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
          UNSPLASH_ACCESS_KEY: ${{ secrets.UNSPLASH_ACCESS_KEY }}
        run: python main.py
